export const LIMITS = {
  MAX_FILE_SIZE_BYTES: 10 * 1024 * 1024, // 10 MB
  MAX_DOCUMENTS_PER_USER: 20,
  MAX_EXTRACTED_CHARS: 1_200_000,
  MAX_BLOCKS: 3_000,
  MAX_CHARS_PER_BLOCK: 8_000,
  PROCESSING_MAX_DURATION_SECONDS: 60,
  STUCK_PROCESSING_RECLAIM_MINUTES: 5,

  // AI & Retrieval Limits
  AI_FULL_CONTEXT_MAX_CHARS_DEFAULT: 100_000,
  AI_RETRIEVAL_TOP_K_DEFAULT: 8,
  AI_RATE_LIMIT_PER_HOUR_DEFAULT: 15,
  AI_RATE_LIMIT_PER_DAY_DEFAULT: 60,
  AI_MAX_OUTPUT_TOKENS_DEFAULT: 1500,
  AI_TIMEOUT_MS_DEFAULT: 45_000,
} as const;
